on: push
name: deploy
jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@master

    - name: go test
      uses: cedrickring/golang-action@1.3.0

    - name: gcp authenticate
      uses: actions/gcloud/auth@master
      env:
        GCLOUD_AUTH: ${{ secrets.GCLOUD_AUTH }}

    - name: build container image
      uses: actions/gcloud/auth@master
      env:
        CLOUDSDK_CORE_PROJECT: npmfs-242515
      with:
        args: builds submit --tag gcr.io/npmfs-242515/website

    - name: cloud run deploy
      uses: g-harel/gcloud/cli@248
      env:
        CLOUDSDK_CORE_PROJECT: npmfs-242515
      with:
        args: --quiet beta run deploy --image gcr.io/npmfs-242515/website --allow-unauthenticated
          --region=us-central1 --timeout=8s website
