on: push
name: deploy
jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:

      # Setup.
    - uses: actions/checkout@master

      # Run tests. Failure will abort deployment.
    - name: go test
      uses: cedrickring/golang-action@1.3.0

      # Setup gcloud command.
    - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
          version: '275.0.0'
          service_account_key: ${{ secrets.GCLOUD_AUTH }}

      # Build new deployable image.
    - run: gcloud builds submit --tag gcr.io/npmfs-242515/website
      env:
        CLOUDSDK_CORE_PROJECT: npmfs-242515

      # Deploy new image.
    - run: gcloud --quiet run deploy --image gcr.io/npmfs-242515/website --allow-unauthenticated --region=us-central1 --timeout=8s website
      env:
        CLOUDSDK_CORE_PROJECT: npmfs-242515
